INSERT INTO PATIENT VALUES(tpatient(1,'GRIGAHCINE','Nacer','95,Bd Bougara‐El biar‐Alger','021920313','MNAM', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(3,'ABADA','ABDELHAMID','Rue Des Freres Bouchama Bt A Bloc F N 138‐Constantine','031944128','LMDE', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(6,'ABERKANE','Aboukhallil','CITE 500 LOGTS BT 29 N 02 KHROUB‐ Constantine','031963658','MNH', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(13,'MAHBOUBA','Cherifa','CITE 1013 LOGTS BT 61 KHROUB‐ Constantine','031966095','MAAF', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(14,'ACHEUK','Youcef','Rue Des Freres Khaznadar Bt N 28‐ Constantine','031964664','MGEN', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(21,'ACHOUR','Fadila','CITE 1650 LOGTS BT F8 N 71 AIN SMARA‐ Constantine','031974253','MMA', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(23,'AKROUM','Mohammed','Cité Aïssa Harièche,Bâtiment B,n° 12 18000-Jijel','034497088','CNAMTS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(33,'ADJALI','Temim','lot 212 villa n 52 ain smara‐ Constantine','031974214','CCVRP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(35,'HADJ','Haroun','avenue 1er novembre 54‐Sétif','036834401','MNFTC', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(36,'LATRI','Cherifa','cite 600 logts bt a10 n66‐Sétif','036512093','MAS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(37,'SEDDIK AMEUR','Moussa','cite belkhired hacene bt d39 n°593‐Sétif','036722343','AG2R', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(41,'ZENTOUT','Nazih','47,Rue des Frere Niati– Plateaux-Oran','041400805','MGSP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(43,'CHALABI','Mirali','24 rue Larbi Ben Mhidi-0ran','041292275','MNAM', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(44,'BOUABDALLAH','Reda','7è rue n° 394 Tourville-Arzew-W.Oran','0770920566','LMDE', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(46,'BESALAH','Kaddour','112,coop de 18 fevrier ‐St hubert-Oran','041343241','MNH', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(52,'BOUDJELAL','Salim','15,Rue Miloud Benhaddou– Plateaux-Oran','041407746','MAAF', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(55,'AMARA','Med Sofiane','CITE DAKSI BT 09 N 03 CONSTANTINE','031637827','MGEN', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(56,'AMROUNE','Ahmed Lamine','04 RUE MICHELET CONSTANTINE','031923090','MMA', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(60,'AZZI','Kamel','RUE ABANE RAMDANE N 13 CONSTANTINE','031911002','CNAMTS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(61,'BACHTARZI','Faycal','7,RUE BENMELIEK ( EX RUE PINGET) CONSTANTINE','031912244','CCVRP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(63,'BOUZIDI ','kamal','79 RUE BELOUIZDAD BELCOURT‐Alger','021650220','MNFTC', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(65,'MAICH','Sid‐Ali','87,avenue Ali Khodja ‐El Biar‐Alger ','021925219','MAS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(66,'HAFIZ','Mahmoud','01,lot Houari Boumediènne  .SIDI MOUSSA ‐Alger','0770360116','AG2R', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(67,'OUGHANEM','Mohamed','Diar Es Saada,Bt T,N°2 El Madania,Alger','021279526','MGSP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(68,'SERIR','Mustapha','2,rue ait Boudjemaa ‐ Chéraga‐Alger','021361688','MNAM', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(70,'ZEGGAI','Abdelkader','219 route Ain Elbordj Tissemssilt 38000‐Tissemsilt','046496134','LMDE', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(72,'TAHMI','Lamia','CITE BACHEDJARAH BATIMENT 38 ‐Bach Djerrah‐Alger ','021261446','MNH', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(74,'DIAF AMROUNI','Ghania','43,rue Abderrahmane Sbaa Belle vue‐El Harrach‐Alger ','021526166','MAAF', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(75,'MELEK','Chahinaz','HLM Aissat idir cage 9 3ème etage‐El Harrach‐Alger','021828898','MGEN', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(76,'TECHTACHE','Noura','16,route el djamila‐Ain Benian‐Alger','021306517','MMA', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(77,'TOUATI','Widad','14 Rue des frères aoudia‐El Mouradia‐Alger','021690000','CNAMTS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(78,'MAIDAT','Yassine','cité soumam Bt B1 n° 6‐Boufarik‐Blida','025473974','CCVRP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(79,'CHERIF','Nassim','Avenue hanafi hadjress‐Beni Messous‐Alger','0550084741','MNFTC', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(81,'YOUSFI','Mohamed','Résidence Familiale‐Hussein Dey‐Alger','021479918','MAS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(90,'YASRI','Hocine','6 rue med Fellah Kouba‐Alger','021286589','AG2R', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(91,'BAKIR','Adel','Cogral 1 rue de gao nouveau port alger','0555037013','MGSP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(92,'ABLOUL','Faiza','Cité diplomatique Bt Bleu 14B n°3 Dérgana‐ Alger','021217888','MNAM', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(100,'HORRA','Assia','32 rue Ahmed Ouaked‐Dely Brahim‐Alger','021919105','LMDE', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(101,'MESBAH','Souad','Résidence Chabani‐Hydra‐Alger','021602311','MNH', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(102,'LAAOUAR','Ali','CITÉ 1ER MAI EX 137 LOGEMENTS‐Adrar','049963143','MAAF', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(103,'DRIZI','Djamel','36 hai salem. 2000‐Chlef','027722020','MNAM', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(104,'HADJADJ','Boumediene','EPSP ksar el hirane LAGHOUAT','0661646970','LMDE', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(105,'GROUDA','Houda','EPSP thniet elabed batna','0773516149','MNH', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(107,'MEDJAHED','Ahmed','CITE el naaser‐Ain Touta‐Batna','033835858','MAAF', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(108,'IDJAAD','Mohand','504 logts bt 07‐Akbou‐Bejaia','034353567','MGEN', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(109,'KACI','Ali','08 Rue SEFACENE Ahmed‐El‐Kseur‐Bejaia','034252429','MMA', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(117,'KECIR','Laziz','av hassiba benbouali‐Béjaïa','034217564','CNAMTS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(119,'FENNICHE','Saida','cite de l’indépendance larbaa blida','025466475','CCVRP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(120,'KOUBA','Mohamed','CENTRE BENCHAABANE‐Ben Khellil‐Blida','025470276','MNFTC', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(121,'AOUIZ','Messoud','Rue Saidani Abdesslam ‐Ain Bessem‐Bouira','026974956','MAS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(123,'OUADAHI','Djaffar','rue amar makhlouf m\chedallah bouira','0554180643','AG2R', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(124,'MIMOUNI','Salah','bp 474 tamanrasset','0550993505','MGSP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(128,'TOUMI','Ahmed','cite 5 juillet BP n° 294‐In Salah‐Tamanrasset','029360311','MNAM', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(133,'TRAD','Abd elkader','El Ogla el Malha‐Tébessa','037447300','LMDE', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(137,'SAADI','Med Tayeb','route strategique 12000‐Tébessa','037481154','MNH', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(138,'HALFAOUI','Redouane','Aderb krima rue des frères benchekra‐Tlemcen','0779719617','MAAF', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(145,'KEDJNANE','Brahim','cité des 48 lgts‐Sougueur‐Tiaret','0663125949','MGEN', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(146,'FADEL','Abderahmane','Cité Rousseau Bt D‐Tiaret','046451212','MMA', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(147,'BENNABI','Ahmed','cité 120 logts bt C n° 11. 15600‐Tigzirt‐Tizi Ouzou','026258494','CNAMTS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(148,'AKIL','Farid','3 rue Larbi Ben Mhidi‐Draa El Mizan‐Tizi Ouzou','026234316','CCVRP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(149,'DIAF','Ali','Rue Ali Abdelmoumen‐Tigzirt‐Tizi Ouzou','026259630','MNFTC', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(153,'CHERFI','Rabah','Hassi Bahbah‐Hassi Bahbah‐Djelfa','027863306','MAS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(154,'RABOUZI','Mohamed','Cité Mohamed Chaounan bloc 831‐02‐Djelfa','0665781440','AG2R', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(158,'HMIA','Seddik','25 rue Ben Yahiya‐Jijel','034472300','MGSP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(159,'MERABET','Ourida','19 Av. Ben Yahiya‐Jijel','034472300','MNAM', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(164,'OUALI','Samia','cité 200 logements bt1 n°1‐Jijel','034501028','LMDE', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(166,'HADDAD','Fatiha','rue boufada lakhdarat‐Ain Oulmène‐Setif','036720221','MNH', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(167,'MATI','Djamel','Draa kebila hammam guergour sétif','0664504332','MAAF', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(168,'Maiza','Rima','Cité brarma n 5‐Sétif','0774208681','MGEN', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(171,'RAFFAOUI','Meriem','Rue MERIEM BOUATOURA SETIF','0557541887','MMA', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(172,'ZERARGA','Mustapha','Cité Hachemi D2 N° 18 Sétif','0551269045','CNAMTS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(175,'OUCHERIT','Aissa','43,Rue Larbi Ben Mhidi-Oran','041406670','CCVRP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(181,'GHRAIR','Mohamed','Cité Jeanne d’Arc Ecran B5‐Gambetta-Oran','041531208','MNFTC', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(182,'MOUHTADI','Dalila','6,Bd Tripoli-Oran','041391640','MAS', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(184,'CHALAH','Younes','cité des 60logts bt D n° 48‐Naciria‐Boumerdes','024880106','AG2R', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(187,'HAMIDI','Mahfoud','BP 24 G Frantz Fanon‐Boumerdes','0771500169','MGSP', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(188,'TITOUCHE','Mohamed','Cité des 50 logts. Sidi Daoud‐Boumerdes','024891120','MNAM', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(190,'BARKAT','Boubeker','CITE MENTOURI N 71 BT AB SMK Constantine','031688561','LMDE', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(191,'DJAKANI','Mostafa','hai nasr‐Tindouf','049934241','MNH', t_set_medecin(), NULL));
INSERT INTO PATIENT VALUES(tpatient(192,'HABABB','khadra','Cité lakssabi‐Tindouf','049922543','MAAF', t_set_medecin(), NULL));
