INSERT INTO medecin VALUES(tmedecin(196,'TEBIBEL','Nabila','33,rue du Hoggar‐Hydra‐Alger','021604840',check_medecin_spec('Traumatologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(4,'BOUROUBI','Taous','Lotissement Dauphin n°30 DRARIA/ALGER','021356085',check_medecin_spec('Orthopédiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(7,'BOUZIDI','AMEL','En face brigade gendarmerie‐Douera‐Alger','0556863528',check_medecin_spec('Cardiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(8,'LACHEMI','Bouzid','140,Av Ali Khoudja‐El Biar‐Alger','021928568',check_medecin_spec('Cardiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(10,'BOUCHEMLA','Elias','6,hai sidi serhane ‐Khemis El Khechna‐Boumerdes','024873549',check_medecin_spec('Cardiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(180,'FEKAR','Abdelaziz','Cité Garidi 1 Bt 38,N° 9‐Kouba‐Alger','021687563',check_medecin_spec('Cardiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(179,'MOHAMMEDI','Mustapha','42 Ber El‐Djir‐Oran','0771255642',check_medecin_spec('Anesthésiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(152,'BOULARAS','Fatima','21,rue Ferhat Boussaad‐Alger','021237998',check_medecin_spec('Cardiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(140,'TERKI','Amina','17 Rue Mohammed CHABANI‐Alger Centre‐Alger','021235894',check_medecin_spec('Cardiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(141,'CHAOUI','Farid','13,rue khawarismi ‐Kouba‐Alger','021234163',check_medecin_spec('Traumatologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(144,'BENDALI','Hacine','Cité Sonelgaz N° 31‐Ben Aknoun‐Alger','0663163973',check_medecin_spec('Radiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(135,'RAHALI','Ahcene','105,Lot Oued Tarfa‐Draria‐ALGER','0557705901',check_medecin_spec('Anesthésiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(99,'BASSI','Fatima','Cité du 5 juillet bloc 130‐Mostaganem','045217227',check_medecin_spec('Anesthésiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(113,'BEHADI','Youcef','9 rue B Koucha‐Bordj Bou Arreridj','035681165',check_medecin_spec('Pneumologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(114,'BEKKAT','Hadia','Bd colonele amirouche‐Baba Hassen‐Alger','021481514',check_medecin_spec('Traumatologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(122,'BELAKERMI','Mohammed','Rue de Palestine Sidi Bel Abbes','048544923',check_medecin_spec('Pneumologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(126,'BELGHALI','Mohammed','100 rue Maski Mhamed‐Tipaza','024496636',check_medecin_spec('Radiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(88,'BACHA','Nadia','Cité des 200 logts Bt f n° A‐Ouled Yaich‐Blida','025436875',check_medecin_spec('Cardiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(89,'BAHBOUH','Naima','Cité bonne fontaine‐CHERAGA‐ALGER','0773298155',check_medecin_spec('Radiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(80,'AMARA','Dahbia','Nouvelle villa n°27‐Hammedi‐Boumerdes','024860591',check_medecin_spec('Cardiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(82,'AROUEL','Leila','cite frères SADANE bt 34a‐Guelma','037205906',check_medecin_spec('Orthopédiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(85,'BAALI','Souad','3 rue Aissani Said‐Guelma','037264734',check_medecin_spec('Anesthésiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(19,'AAKOUB','Fatiha','Boulvard Colonel Amirouche‐Sfissef‐Sidi Bel Abbas','048595512',check_medecin_spec('Traumatologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(64,'ADDAD','Fadila','9 cite el hana‐Oum El Bouaghi‐Alger','032421633',check_medecin_spec('Radiologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(50,'ABERKANE','Aicha','Cité des 300 logts N°10‐Bab Ezzouar‐Alger','021248345',check_medecin_spec('Pneumologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(53,'AZOUG','Dalila','64 rue de Tripoli‐Hussein Dey‐Alger','021771170',check_medecin_spec('Traumatologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(54,'BENOUADAH','Mohammed','26,boulevard Said Touati‐Beb el oued‐ALGER','021962035',check_medecin_spec('Pneumologue'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(31,'ABDELAZIZ','Ahmed','43 avenue du 1er novembre‐Ghardaia','029892979',check_medecin_spec('Anesthésiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(34,'ABDELMOUMEN','Nassima','Cité Kharoubi Bt. 18‐Médéa','025584204','Pneumologue', t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(26,'ABBACI','Abdelmadjid','14 rue Ouabdelkader‐Bejaia','034201409',check_medecin_spec('Orthopédiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(27,'ABBAS','Samira','22 rue ahmaed aoune el harrach‐alger','0664027500',check_medecin_spec('Orthopédiste'), t_set_patient()));
INSERT INTO medecin VALUES(tmedecin(24,'ABADA','Mohamed','2 rue del\Abreuvoir‐Alger','021737000',check_medecin_spec('Orthopédiste'), t_set_patient()));
